// Generated by CoffeeScript 1.9.1
var coffee, gulp, jade, stylus, yaml;

gulp = require('gulp');

coffee = require('gulp-coffee');

jade = require('gulp-jade');

stylus = require('gulp-stylus');

yaml = require('gulp-yaml');

gulp.task('default', ['coffee', 'jade', 'styl', 'yaml']);

gulp.task('watch', function() {
  return gulp.watch('./src/**', ['default']);
});

gulp.task('coffee_gulpfile', function() {
  return gulp.src('./gulpfile.coffee').pipe(coffee({
    bare: true
  })).pipe(gulp.dest('./'));
});

gulp.task('jade', function() {
  return gulp.src('./src/**/*.jade').pipe(jade({
    pretty: true
  })).pipe(gulp.dest('./build'));
});

gulp.task('coffee', function() {
  return gulp.src('./src/**/*.coffee').pipe(coffee({
    bare: true
  })).pipe(gulp.dest('./build'));
});

gulp.task('styl', function() {
  return gulp.src('./src/**/*.styl').pipe(stylus({})).pipe(gulp.dest('./build'));
});

gulp.task('yaml', function() {
  return gulp.src('./src/**/*.yml').pipe(yaml({
    space: 4
  })).pipe(gulp.dest('./build'));
});
